import { Heading } from '@ionext-ui/react'
import Head from 'next/head'
import { Roboto } from 'next/font/google'
const roboto = Roboto({ subsets: ['latin'], weight:['300','400','500','700'] })
export default function Home() {
  return (
    <>
      <Head >
        <title>Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Heading size={'sm'} >
        Hello Word
        </Heading>
      </div>
    </>
  )
}
