name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ">=18.16.0"
      - name: Install Dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint .
      - name: Typescript
        run: npm run tsc
      - name: Run Build
        run: npm run build
