name: CI2
 
on: push
 
jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      env:
       TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
       TURBO_TEAM: ${{ secrets.VERCEL_TEAM }}
       TURBO_REMOTE_ONLY: true
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: ">=18.16.0"
            cache: 'npm'
 
        - name: Install dependencies
          run: npm install

        - name: Run Linter
          run: npm run lint .

        - name: Typescript
          run: npm run tsc
 
        - name: Build
          run: npm run build
        
        
 
   